#ifndef WAI_ORB_MATCHING_H
#define WAI_ORB_MATCHING_H

#include <WAIPlatform.h>

#define ROTATION_HISTORY_LENGTH 30
#define MATCHER_DISTANCE_THRESHOLD_LOW 50
#define MATCHER_DISTANCE_THRESHOLD_HIGH 100

#endif
